export type Podcast = { slug:string; title:string; category:string; age:string; duration:string; color:string; accent:string; icon:string; summary:string; episodes:{title:string;copy:string}[] };

export const podcasts: Podcast[] = [
  { slug:"terre-academie", title:"Terre Académie", category:"Sciences & nature", age:"8–12 ans", duration:"12 min", color:"#aaa0dc", accent:"#9fdad8", icon:"🌎", summary:"Une aventure sonore sur une île où chaque défi révèle un secret de la planète.", episodes:[{title:"Débarquer",copy:"Une arrivée mouvementée et une mission qui ne ressemble à aucune autre."},{title:"Protéger et servir",copy:"De petits oiseaux transforment complètement le plan du jour."},{title:"S’informer",copy:"Une vidéo mystérieuse met l’esprit critique de l’équipe à l’épreuve."}] },
  { slug:"facteur-espace", title:"Le facteur de l’espace", category:"Contes & histoires", age:"6–10 ans", duration:"9 min", color:"#9fdad8", accent:"#f16e4f", icon:"🚀", summary:"Un facteur intergalactique livre des colis impossibles aux quatre coins de l’univers.", episodes:[{title:"Le colis qui chantait",copy:"Une boîte fredonne une mélodie inconnue dans la soute."},{title:"Adresse inconnue",copy:"Une planète déménage sans laisser de nouvelle adresse."},{title:"Le dernier timbre",copy:"Bob doit choisir entre rentrer et terminer sa tournée."}] },
  { slug:"memos-vocaux", title:"Mémos vocaux", category:"Émotions & intimité", age:"10–14 ans", duration:"7 min", color:"#f49a91", accent:"#7eb6f2", icon:"💬", summary:"Des messages jamais envoyés racontent les grandes émotions des petites journées.", episodes:[{title:"Je recommence",copy:"Un message effacé douze fois avant d’être enfin gardé."},{title:"Le bruit dans ma tête",copy:"Quand une pensée minuscule prend toute la place."},{title:"Envoyer",copy:"Le courage tient parfois dans un seul bouton."}] },
  { slug:"bonnes-nouvelles", title:"Le journal des bonnes nouvelles", category:"Société & histoire", age:"8–13 ans", duration:"11 min", color:"#f3df42", accent:"#b4d33b", icon:"🗞️", summary:"Une rédaction curieuse cherche les nouvelles qui donnent envie d’agir.", episodes:[{title:"La ville aux mille jardins",copy:"Des voisins transforment des espaces oubliés en potagers."},{title:"Une bibliothèque sur roues",copy:"Les livres prennent la route vers de nouveaux lecteurs."},{title:"Le défi des réparateurs",copy:"Réparer plutôt que jeter devient une aventure collective."}] },
  { slug:"expressions", title:"J’adore cette expression !", category:"Arts & culture", age:"7–12 ans", duration:"6 min", color:"#bda8ef", accent:"#f16e4f", icon:"🎭", summary:"Pourquoi donne-t-on sa langue au chat et tombe-t-on dans les pommes ?", episodes:[{title:"Donner sa langue au chat",copy:"Une enquête poilue sur une expression très ancienne."},{title:"Tomber dans les pommes",copy:"Des fruits, un malaise et une origine discutée."},{title:"Avoir le cafard",copy:"Comment un insecte est-il devenu une émotion ?"}] },
  { slug:"voix-lactee", title:"La voix lactée", category:"Contes & histoires", age:"5–10 ans", duration:"8 min", color:"#7eb6f2", accent:"#f3df42", icon:"🌌", summary:"Chaque étoile possède une voix, mais une seule enfant sait encore les écouter.", episodes:[{title:"L’étoile muette",copy:"Une lumière clignote sans produire le moindre son."},{title:"La carte du ciel",copy:"Une constellation dessine un chemin inattendu."},{title:"Le concert de minuit",copy:"Toutes les voix du ciel se réunissent enfin."}] },
];
