"use client";
import { FormEvent, useMemo, useState } from "react";
import { podcasts, type Podcast } from "./data";

const nav = [{href:"/",label:"Accueil"},{href:"/evenements/",label:"Événements"},{href:"/affiches-amplifiees/",label:"Affiches amplifiées"},{href:"/a-propos/",label:"À propos"},{href:"/mediation/",label:"Médiation"}];

function Logo(){ return <a className="logo" href="/"><b>La puce</b><b>à l’oreille</b><small>maquette indépendante</small></a> }
function Header(){ const [menu,setMenu]=useState(false); const [explore,setExplore]=useState(false); return <header><Logo/><button className="mobile" onClick={()=>setMenu(!menu)}>{menu?"×":"☰"}</button><nav className={menu?"open":""}><div className="explore"><button className="pill" onClick={()=>setExplore(!explore)}>Explorer <i/></button>{explore&&<div className="drop"><a href="/#podcasts">Balados</a><a href="/#podcasts">Collaborations</a><a href="/#podcasts">Durée</a><a href="/#podcasts">Thématiques</a><a href="/#podcasts">Tranche d’âge</a></div>}</div>{nav.slice(1,3).map(x=><a className="pill" href={x.href} key={x.href}>{x.label}</a>)}</nav><nav className="mini">{nav.slice(3).map(x=><a href={x.href} key={x.href}>{x.label}</a>)}</nav></header> }
function Stripes(){ return <aside className="stripes"><i/><i/><i/><i/></aside> }
function Art({p,big=false}:{p:Podcast,big?:boolean}){ return <div className={`art ${big?"big":""}`} style={{background:p.color}}><span className="planet"/><b>{p.icon}</b><strong>{p.title}</strong><i style={{background:p.accent}}/></div> }
function Player({p}:{p:Podcast}){ const [on,setOn]=useState(false); return <button className={`play ${on?"on":""}`} onClick={()=>setOn(!on)} aria-label={`Écouter ${p.title}`}>{on?"Ⅱ":"▶"}</button> }
function Card({p}:{p:Podcast}){ return <article className="card"><a href={`/balado/${p.slug}/`}><Art p={p}/><div className="cardbody"><span className="tag" style={{background:p.accent}}>{p.category}</span><small>{p.age} · {p.duration}</small><h2>{p.title}</h2><p>{p.summary}</p><u>En savoir plus</u></div></a><Player p={p}/></article> }
function Footer(){ const [ok,setOk]=useState(false); return <footer><section><h2>S’abonner à<br/>nos fils audio</h2>{ok?<strong>✓ Vous êtes sur la liste !</strong>:<form onSubmit={(e)=>{e.preventDefault();setOk(true)}}><input type="email" required placeholder="Votre adresse courriel"/><button>S’abonner ↗</button></form>}</section><div><Logo/><nav><a href="/confidentialite/">Confidentialité</a><a href="/contact/">Contact</a><a href="/a-propos/">À propos</a><a href="/infolettre/">Infolettre</a></nav><p>Une recréation visuelle indépendante.</p></div></footer> }
function Shell({children}:{children:React.ReactNode}){ return <div className="site"><div className="curtain"><i/><i/><i/><i/></div><Header/><main>{children}</main><Footer/><Stripes/></div> }

function Home(){ const filters=["Tous","Sciences","Histoires","Émotions","Culture"]; const [filter,setFilter]=useState("Tous"); const [random,setRandom]=useState<Podcast|null>(null); const list=useMemo(()=>filter==="Tous"?podcasts:podcasts.filter(p=>p.category.includes(filter)),[filter]); return <Shell><section className="hero"><span className="doodle d1">🎧</span><span className="doodle d2">🎙️</span><span className="doodle d3">🪐</span><span className="doodle d4">✎</span><h1>Balados<br/>décalés pour<br/>enfants<br/><em>allumés</em></h1><div className="note">Des histoires sonores pour éveiller la curiosité, rire, apprendre et regarder le monde autrement.</div></section><section className="discover"><div className="burst">Curieux</div><div className="disc"><b>EXPLORER NOS PRODUCTIONS</b><div>{filters.map(f=><button className={f===filter?"selected":""} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div></div><button className="random" onClick={()=>setRandom(podcasts[Math.floor(Math.random()*podcasts.length)])}><span>{random?random.title:"Écoute aléatoire"}</span><b>▶</b></button></section><section id="podcasts" className="catalog"><div className="titleline"><span>Nouveautés</span><h2>À écouter maintenant</h2><b>{String(list.length).padStart(2,"0")}</b></div><div className="grid">{list.map(p=><Card p={p} key={p.slug}/>)}</div></section><section className="question"><div><small>ALLÔ LA PUCE</small><h2>Pose une question<br/>à notre équipe</h2></div><a href="/contact/">●<span>Enregistrer<br/>un message</span></a></section></Shell> }
function Balado({p}:{p:Podcast}){ return <Shell><section className="detailHero"><div><span className="tag" style={{background:p.accent}}>{p.category}</span><h1>{p.title}</h1><small>{p.age} · {p.duration}</small><p>{p.summary} Une série originale qui invite à écouter attentivement et à laisser l’imagination prendre le relais.</p></div><div className="poster"><Art p={p} big/><div className="seal" style={{background:p.accent}}>NOUVELLE<br/>SÉRIE</div></div></section><section className="episodes"><div className="titleline"><span>Saison 01</span><h2>Épisodes</h2><b>03</b></div>{p.episodes.map((e,i)=><article key={e.title}><b>{String(i+1).padStart(2,"0")}</b><div><small>ÉCOUTE !</small><h3>{e.title}</h3><p>{e.copy}</p></div><button>▶<span>Écouter</span></button></article>)}</section><section className="catalog more"><h2>Découvrir aussi</h2><div className="grid">{podcasts.filter(x=>x.slug!==p.slug).slice(0,2).map(x=><Card p={x} key={x.slug}/>)}</div></section></Shell> }
const events=[{date:"24.08",title:"Les oreilles en fête",text:"Une journée de découvertes sonores, de créations et d’histoires pour toute la famille."},{date:"07.09",title:"Fabrique ton balado",text:"De l’idée au micro: un atelier pratique pour imaginer et enregistrer une émission."},{date:"21.09",title:"Raconter sans écran",text:"Une rencontre pour faire vivre l’audio auprès des enfants."}];
function Events(){ return <Shell><section className="page"><small>RENDEZ-VOUS SONORES</small><h1>Événements</h1><div className="eventlist">{events.map((e,i)=><article key={e.title}><time>{e.date}<small>2026</small></time><div><span className="tag">Tout public</span><h2>{e.title}</h2><p>{e.text}</p></div><a href="/contact/">Réserver ↗</a></article>)}</div></section></Shell> }
function Posters(){ return <Shell><section className="page posters"><small>ÉCOUTER AVEC LES YEUX</small><h1>Affiches<br/>amplifiées</h1><p className="lead">Des affiches qui déclenchent une histoire. Choisissez un univers, approchez-vous et laissez le son agrandir l’image.</p><div className="postergrid">{podcasts.slice(0,4).map((p,i)=><article key={p.slug} style={{background:p.color}}><span>{p.icon}</span><h2>{p.title}</h2><button>Scanner & écouter ↗</button></article>)}</div></section></Shell> }
function About({mediation=false}:{mediation?:boolean}){ return <Shell><section className="page about"><small>{mediation?"OUTILS · ATELIERS · FORMATIONS":"QUI SOMMES-NOUS ?"}</small><h1>{mediation?"Médiation":"À propos"}</h1><div className="mission"><h2>{mediation?"Faire ensemble":"Notre mission"}</h2><p><b>La puce à l’oreille</b> imagine des expériences audio destinées aux enfants et aux adolescents. La création, la transmission et la curiosité sont au cœur de chaque projet.</p><p>{mediation?"Nos ateliers accompagnent les jeunes dans l’écoute, l’écriture, la prise de parole et la fabrication d’un récit sonore.":"Nous croyons que des contenus exigeants, drôles et sensibles aident les jeunes à devenir des auditeurs critiques et des citoyens éclairés."}</p></div><div className="values"><article><b>01</b><h3>Imaginer</h3><p>Des mondes qui prennent vie sans écran.</p></article><article><b>02</b><h3>Écouter</h3><p>Les voix, les silences et ce qui nous entoure.</p></article><article><b>03</b><h3>Partager</h3><p>Des outils accessibles pour petits et grands.</p></article></div></section></Shell> }
function Contact(){ const [sent,setSent]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)}; return <Shell><section className="page contact"><small>UN MESSAGE POUR NOUS ?</small><h1>Contact</h1><div className="contactgrid"><div className="bubble">Allô !<small>Qu’aimeriez-vous nous raconter ?</small></div>{sent?<div className="thanks"><b>✓</b><h2>Message enregistré</h2><p>Merci ! Cette maquette a bien validé le formulaire.</p></div>:<form onSubmit={submit}><label>Nom<input required/></label><label>Courriel<input required type="email"/></label><label>Sujet<select><option>Une question</option><option>Un projet</option><option>Un atelier</option></select></label><label>Message<textarea required rows={6}/></label><button>Envoyer ↗</button></form>}</div></section></Shell> }
export default function Experience({route="home",slug}:{route?:string;slug?:string}){ const p=podcasts.find(x=>x.slug===slug); if(p)return <Balado p={p}/>; if(route==="evenements")return <Events/>; if(route==="affiches-amplifiees")return <Posters/>; if(route==="a-propos")return <About/>; if(route==="mediation")return <About mediation/>; if(["contact","confidentialite","infolettre"].includes(route))return <Contact/>; return <Home/> }
